### ISSUE TITLE
Edirom Editor 1.1.26_win32_x86 won't start

### ISSUE THREAD

**Issue by Herrner** [Edirom/Edirom-Editor#1]
Running the .exe file results in "Java was started but returned exit code=13
![unbenannt](https://cloud.githubusercontent.com/assets/2045460/20394545/3170f822-ace0-11e6-8bee-d2adf146ae5f.PNG)

**Comment by bwbohl** [comment]
Which java version do you have installed?

**Comment by Herrner** [comment]
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

**Comment by Herrner** [comment]
I tried launching the launcher-jar manually and got

> org.osgi.framework.BundleException: The activator org.eclipse.ui.internal.WorkbenchPlugin for bundle org.eclipse.ui.workbench is invalid

in the log file - it seems that it will only run on 32bit java: After installing a 32bit VM I am able to run the .exe.

**Comment by bwbohl** [comment]
ok, perfect, I was just about to write you. Sorry setting up a test machine took a bit…
