### ISSUE TITLE
Edirom Editor 1.1.26_macosx_x86 won't start

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Editor#2]
The Edirom Editor from the relase won't start in macOS Sierra 10.12.2, and abort with the alert:
![screen shot 2017-01-16 at 14 57 05](https://cloud.githubusercontent.com/assets/2430401/21985704/47c59682-dbfc-11e6-96a5-1bc6fc9b2d2a.png)

**Comment by bwbohl** [comment]
Starting it from the app contents MacOS/Edirom Editor with a double-click works though.

**Comment by bwbohl** [comment]
as this software is no longer under development I label this issue wontfix

**Comment by roewenstrunk** [comment]
This issue will be closed because the software is no longer maintained.
